// This file was generated by Prisma, and assumes you have installed the following:
// npm install --save-dev prisma dotenv
import "dotenv/config";
import { defineConfig } from "prisma/config";

export default defineConfig({
  schema: "prisma/schema.prisma",
  migrations: {
    path: "prisma/migrations",
  },
  datasource: {
    url: "postgresql://postgres.zympcihvfsxdlxuvaqtc:rK2ik0G338m6986Z@aws-1-eu-west-1.pooler.supabase.com:5432/postgres",
  },
});
